branch-defaults:
  default:
    environment: shopify-apparel21-connector-staging
environment-defaults:
  shopify-apparel21-connector-staging:
    branch: null
    repository: null
global:
  application_name: shopify-apparel21-connector
  default_ec2_keyname: shopify-apparel21-syncer
  default_platform: PHP 7.0
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
